pagehelper:
  dialect-alias: alias1=com.github.pagehelper.dialect.helper.MySqlDialect;
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pinyougoudb?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapper-locations: classpath:com/pinyougou/mapper/*.xml
  type-aliases-package: com.pinyougou.pojo